CREATE FUNCTION ALBERTOS1/FILSST ( P_STRING CHAR(21))
RETURNS CHAR(10)

  BEGIN
   DECLARE FIL CHAR(10);
   DECLARE POS INTEGER ;
   DECLARE LEN INTEGER ;

   SET POS = LOCATE('/', P_STRING);
   SET LEN = LENGTH(TRIM(P_STRING));
   SET FIL = SUBSTRING(P_STRING, POS+1, LEN-POS);
   RETURN FIL;
  END;
