CREATE OR REPLACE FUNCTION CRYPTMSK0O/OBJSST ( P_STRING CHAR(21))
RETURNS CHAR(10)

  BEGIN
   DECLARE OBJ CHAR(10);
   DECLARE POS INTEGER ;
   DECLARE LEN INTEGER ;

   SET POS = LOCATE('/', P_STRING);
   SET LEN = LENGTH(TRIM(P_STRING));
   SET OBJ = SUBSTRING(P_STRING, POS+1, LEN-POS);
   RETURN OBJ;
  END;
